dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
  - OpenZeppelin/openzeppelin-contracts@4.9.3

compiler:
  solc:
    version: 0.8.2
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3'
    
networks:
  default: sepolia
  sepolia:
    aggregatorv3interface: '0x694AA1769357215DE4FAC081bf1f309aDC325306'

wallets:
  from_key: ${PRIVATE_KEY}

dotenv: .env



  
